### ISSUE TITLE
Error on first run

### ISSUE THREAD

**Issue by bobvandevijver** [kriskbx/gitlab-time-tracker-taskbar#2]
Steps to reproduce:
1. git clone
2. yarn install
3. yarn run start

There is only a gtt-configuration (yml) with the gitlab url and token in the home/.gtt directory. It is run from the git bash on Windows 10 x74, with Node v8.11.2 and Yarn v1.5.1.

```
App threw an error during load
SyntaxError: Unexpected token . in JSON at position 192
    at JSON.parse (<anonymous>)
    at createCompilerHostFromConfigFileSync (C:\Users\Bob\Documents\Git\opensource\gitlab-time-tracker-taskbar\node_modules\electron-compile\lib\config-parser.js:387:19)
    at createCompilerHostFromProjectRootSync (C:\Users\Bob\Documents\Git\opensource\gitlab-time-tracker-taskbar\node_modules\electron-compile\lib\config-parser.js:409:12)
    at init (C:\Users\Bob\Documents\Git\opensource\gitlab-time-tracker-taskbar\node_modules\electron-compile\lib\config-parser.js:290:20)
    at main (C:\Users\Bob\Documents\Git\opensource\gitlab-time-tracker-taskbar\node_modules\electron-prebuilt-compile\lib\es6-init.js:58:29)    at Object.<anonymous> (C:\Users\Bob\Documents\Git\opensource\gitlab-time-tracker-taskbar\node_modules\electron-prebuilt-compile\lib\es6-init.js:61:1)
    at Object.<anonymous> (C:\Users\Bob\Documents\Git\opensource\gitlab-time-tracker-taskbar\node_modules\electron-prebuilt-compile\lib\es6-init.js:63:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```

**Comment by kriskbx** [comment]
Please delete the `C:\Users\Bob\.gtt\cache` folder and try again. :)

**Comment by bobvandevijver** [comment]
That folder was empty, and removing it unfortunately did not help

**Comment by kriskbx** [comment]
Sorry for the inconvenience: there was a typo in the compilerc config. Please pull and try again. :)

**Comment by bobvandevijver** [comment]
Yes, that does work! :) Interesting how such a small thing complete breaks everything. Will test it some more in the coming time!
