### ISSUE TITLE
Start/stop/cancel button have no impact without restarting application

### ISSUE THREAD

**Issue by bobvandevijver** [kriskbx/gitlab-time-tracker-taskbar#3]
Either one of the buttons do not do anything until you restart the application. The log below is from starting on an issue, quitting the app, and then restarting it. 

Key seems to be working just fine, as the issues and projects are loading.

```
Bob@BOBV-LAPTOP MINGW64 ~/Documents/Git/opensource/gitlab-time-tracker-taskbar (master)
$ yarn start run
yarn run v1.5.1
$ electron-forge start run
√ Checking your system
√ Locating Application
√ Preparing native dependencies
√ Launching Application

Done in 120.71s.

Bob@BOBV-LAPTOP MINGW64 ~/Documents/Git/opensource/gitlab-time-tracker-taskbar (master)
$ yarn start run
yarn run v1.5.1
$ electron-forge start run
√ Checking your system
√ Locating Application
√ Preparing native dependencies
√ Launching Application

Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments:
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: false, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (C:\Users\Bob\Documents\Git\opensource\gitlab-time-tracker-taskbar\node_modules\moment\moment.js:320:98)
    at configFromInput (C:\Users\Bob\Documents\Git\opensource\gitlab-time-tracker-taskbar\node_modules\moment\moment.js:2606:19)
    at prepareConfig (C:\Users\Bob\Documents\Git\opensource\gitlab-time-tracker-taskbar\node_modules\moment\moment.js:2577:13)
    at createFromConfig (C:\Users\Bob\Documents\Git\opensource\gitlab-time-tracker-taskbar\node_modules\moment\moment.js:2544:44)
    at createLocalOrUTC (C:\Users\Bob\Documents\Git\opensource\gitlab-time-tracker-taskbar\node_modules\moment\moment.js:2631:16)
    at createLocal (C:\Users\Bob\Documents\Git\opensource\gitlab-time-tracker-taskbar\node_modules\moment\moment.js:2635:16)
    at hooks (C:\Users\Bob\Documents\Git\opensource\gitlab-time-tracker-taskbar\node_modules\moment\moment.js:12:29)
    at frame.get stop [as stop] (C:\Users\Bob\Documents\Git\opensource\gitlab-time-tracker-taskbar\node_modules\gitlab-time-tracker\src\models\frame.js:106:32)
    at frames.forEach.frame (C:\Users\Bob\Documents\Git\opensource\gitlab-time-tracker-taskbar\node_modules\gitlab-time-tracker\src\models\frameCollection.js:31:22)
    at Array.forEach (native)
(node:8816) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Could not update issue 76 on extern/013-living-textbook
(node:8816) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by kriskbx** [comment]
This was caused by an error in the underlying gtt library (https://github.com/kriskbx/gitlab-time-tracker). I fixed it. Can you pull/download version 0.2.1 and try again?

**Comment by kriskbx** [comment]
Note: It can take up to 20 minutes after pushing commits until continuos integration has build and published the packages. ;)

**Comment by bobvandevijver** [comment]
Unfortunately, it still has the same behaviour.. It just hangs after clicking start (on both the git version, as the executable). It does log the action in the console now (yarn version), but on restart the same error as before is shown.

![image](https://user-images.githubusercontent.com/1835343/40834004-ce4fa846-658f-11e8-98bb-3e82c7f61dcb.png)

**Comment by kriskbx** [comment]
I was finally able to reproduce your problem. Working on it right now. Will probably take some time but I'll keep you up to date in here. :)

**Comment by kriskbx** [comment]
Okay, nevermind. The fix was pretty easy.
Make sure to upgrade to 0.2.2. :)

**Comment by bobvandevijver** [comment]
Seems to be fixed :D

**Comment by SimeonC** [comment]
Hey, I seem to have got this issue again on gtt-taskbar-darwin-x64-0.2.4.zip under OSX 10.13.5.
How do I give you more details/troubleshoot what's wrong on my machine for this?
FYI rebooting the app after each start/stop still saved the time correctly into gitlab - ours is a self hosted gitlab instance.

EDIT: For some reason after a reboot and a few times quit + restart it's working now.

**Comment by SimeonC** [comment]
So now that I've done some playing around with debug open I think this is still an issue in some form. When I see this happen on dev (reloading the app fixes this) I get this in the console.

```
(node:38641) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Could not update issue 17 on ***/***/***
(node:38641) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Feels to me like this is an issue with how gtt-cli and the app integrate together but I can't dig into this further.
